export default (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="61"
        height="67"
        viewBox="0 0 61 67"
        fill="none"
    >
        <rect
            x="2.5"
            y="2.5"
            width="56"
            height="62"
            rx="11.3"
            stroke="#1150CC"
            strokeWidth="5"
        />
        <line
            x1="17.5"
            y1="22.5"
            x2="43.5"
            y2="22.5"
            stroke="#1150CC"
            strokeWidth="5"
            strokeLinecap="round"
        />
        <line
            x1="17.5"
            y1="33.5"
            x2="43.5"
            y2="33.5"
            stroke="#1150CC"
            strokeWidth="5"
            strokeLinecap="round"
        />
        <line
            x1="17.5"
            y1="44.5"
            x2="43.5"
            y2="44.5"
            stroke="#A4D4FF"
            strokeWidth="5"
            strokeLinecap="round"
        />
    </svg>
);
